/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StatsLazyImport = createFileRoute('/stats')()
const SignupLazyImport = createFileRoute('/signup')()
const SigninLazyImport = createFileRoute('/signin')()
const LeaderboardLazyImport = createFileRoute('/leaderboard')()
const GameLazyImport = createFileRoute('/game')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StatsLazyRoute = StatsLazyImport.update({
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stats.lazy').then((d) => d.Route))

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const LeaderboardLazyRoute = LeaderboardLazyImport.update({
  path: '/leaderboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/leaderboard.lazy').then((d) => d.Route))

const GameLazyRoute = GameLazyImport.update({
  path: '/game',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/game.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameLazyImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/game': typeof GameLazyRoute
  '/leaderboard': typeof LeaderboardLazyRoute
  '/signin': typeof SigninLazyRoute
  '/signup': typeof SignupLazyRoute
  '/stats': typeof StatsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/game': typeof GameLazyRoute
  '/leaderboard': typeof LeaderboardLazyRoute
  '/signin': typeof SigninLazyRoute
  '/signup': typeof SignupLazyRoute
  '/stats': typeof StatsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/game': typeof GameLazyRoute
  '/leaderboard': typeof LeaderboardLazyRoute
  '/signin': typeof SigninLazyRoute
  '/signup': typeof SignupLazyRoute
  '/stats': typeof StatsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game' | '/leaderboard' | '/signin' | '/signup' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/leaderboard' | '/signin' | '/signup' | '/stats'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/leaderboard'
    | '/signin'
    | '/signup'
    | '/stats'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GameLazyRoute: typeof GameLazyRoute
  LeaderboardLazyRoute: typeof LeaderboardLazyRoute
  SigninLazyRoute: typeof SigninLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  StatsLazyRoute: typeof StatsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GameLazyRoute: GameLazyRoute,
  LeaderboardLazyRoute: LeaderboardLazyRoute,
  SigninLazyRoute: SigninLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  StatsLazyRoute: StatsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game",
        "/leaderboard",
        "/signin",
        "/signup",
        "/stats"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/game": {
      "filePath": "game.lazy.tsx"
    },
    "/leaderboard": {
      "filePath": "leaderboard.lazy.tsx"
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/stats": {
      "filePath": "stats.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
